apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: orders-cpu-hog
  namespace: litmus
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'sock-shop'
    applabel: 'name=orders'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  monitoring: true
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'orders'

            - name: CPU_CORES
              value: '1'

            - name: TOTAL_CHAOS_DURATION
              value: '240' # in seconds
            
