apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: catalogue-memory-hog
  namespace: litmus
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'sock-shop'
    applabel: 'name=catalogue'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  monitoring: true
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: pod-memory-hog
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'catalogue'

            - name: MEMORY_CONSUMPTION
              value: '500'

            - name: TOTAL_CHAOS_DURATION
              value: '240' # in seconds
            
